---
title: "CoinMarketCap"
author: "Ki Oh"
date: "7/15/2018"
output: pdf_document
---

```{r}
library(coinmarketcapr)
library(treemap)
library(ggplot2)
library(FactoMineR)
library(stats)
library(factoextra)
library(crypto)
library(corrplot)
library(RColorBrewer)
library(pdac)
#plot_top_5_currencies()
```

plot_top_5_currencies()
```{r}
plot_top_5_currencies()
market_today <- get_marketcap_ticker_all()
head(market_today[,1:8])

df1 <- na.omit(market_today[,c('symbol','market_cap_usd', 'percent_change_24h', 'price_btc', 'percent_change_7d', 'total_supply','X24h_volume_usd', 'available_supply')])
head(df1)


```


```{r}
#as numeric
df1$market_cap_usd <- as.numeric(df1$market_cap_usd)
df1$percent_change_24h <- as.numeric(df1$percent_change_24h)
df1$price_btc <- as.numeric(df1$price_btc)
df1$percent_change_7d <- as.numeric(df1$percent_change_7d)
df1$total_supply <- as.numeric(df1$total_supply)
df1$X24h_volume_usd <- as.numeric(df1$X24h_volume_usd)
df1$available_supply <- as.numeric(df1$available_supply)

df1$formatted_market_cap <-  paste0(df1$id,'\n','$',format(df1$market_cap_usd,big.mark = ',',scientific = F, trim = T))

cryptolist <- df1[1:50, 2:8]
row.names(cryptolist) <- df1[1:50,1]
head(cryptolist)

```

```{r}

#Tree Map
treemap(df1, index = 'formatted_market_cap', vSize = 'market_cap_usd', title = 'Cryptocurrency Market Cap', fontsize.labels=c(12, 8), palette='RdYlGn')


#========
df1 <- na.omit(market_today[,c('id','market_cap_usd')])
df1$market_cap_usd <- as.numeric(df1$market_cap_usd)
df1$formatted_market_cap <-  paste0(df1$id,'\n','$',format(df1$market_cap_usd,big.mark = ',',scientific = F, trim = T))
treemap(df1, index = 'formatted_market_cap', vSize = 'market_cap_usd', title = 'Cryptocurrency Market Cap', fontsize.labels=c(12, 8), palette='RdYlGn')
#========

```

#Correlation Analysis
```{r}
res<-cor(t(cryptolist))
round(res,2)
#res<-matrix(res)
head(res)

corrplot(res,type="upper")
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, cl.cex=0.1)
```


```{r}

res.pca <- prcomp(cryptolist, scale = TRUE)
fviz_eig(res.pca)
#graph of coins, similar group together
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,     # Avoid text overlapping
             axes = c(1,3)
)
```

```{r}
#graph variables - positively correlated point to same side. negative point opposite
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE ,    # Avoid text overlapping
             axes = c(1,3)
)

```

```{r}
#Biplot
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  ,# Individuals color
                axes = c(1,2)
)

```

```{r}

library(treemap)
df1 <- na.omit(market_today[,c('id','market_cap_usd')])
df1$market_cap_usd <- as.numeric(df1$market_cap_usd)
df1$formatted_market_cap <-  paste0(df1$id,'\n','$',format(df1$market_cap_usd,big.mark = ',',scientific = F, trim = T))
treemap(df1, index = 'formatted_market_cap', vSize = 'market_cap_usd', title = 'Cryptocurrency Market Cap', fontsize.labels=c(12, 8), palette='RdYlGn')

```



```{r}
ch<-crypto_history(limit=5)
ch2.0<-crypto2xts(ch)

cp<-crypto_prices()
m<-daily_market('bitcoin')
m
ac<-global_market()
#getCoins()
```


```{r}

market<-crypto::daily_market("ETH")

head(market)
plot(x=market$timestamp, y=market$price_usd)
plot(x=market$timestamp, y=market$volume)
plot(x=market$timestamp, y=market$market_cap)
```


```{r}

#df2<-data.frame(cbind(mean1,mean2,mean3,mean4,mean5,mean6))
rownames(df1)<-df1$symbol
df1<-df1[,-1]
res<-cor((cryptolist))
round(res,2)
#res<-matrix(res)
head(res)

corrplot(res,type="upper")
corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, cl.cex=0.1)

```


```{r}
library("Hmisc")
res2 <- rcorr(as.matrix(t(cryptolist)))
res2
res3<-subset(res2,res2$P<0.01)
flattenCorrMatrix(res2$r, res2$P)
# Insignificant correlation are crossed
corrplot(res3$r, type="upper", order="hclust", 
         p.mat = res3$P, sig.level = 0.01, insig = "blank")
# Insignificant correlations are leaved blank
corrplot(res2$r, type="upper", order="hclust", 
         p.mat = res2$P, sig.level = 0.01, insig = "blank")

# Get some colors
col<- colorRampPalette(c("blue", "white", "red"))(20)
heatmap(x = res, col = col, symm = TRUE)
```


```{r, fig.width=15, fig.height=15, message=FALSE, warning=FALSE, echo=FALSE}
#==========================================
#df<-t(cryptolist)
#==========================================
# display result

RowSideColors <- getSideColors(
  sampInfo = cryptolist,
  sampleTracks = c("market_cap_usd",
                   "percent_change_7d"
                 ),
  colorlists = list(c("white","blue"),
               c("white","red")
                    ) ,
  drop.levels = FALSE)

ColSideColors <- getSideColors(
  sampInfo = cryptolist,
  sampleTracks = c( 
                   "market_cap_usd",
                   "percent_change_7d"
 ),
  colorlists = list(
                    c("white","red"),
                    c("white","brown")
         
  )
)

# color scheme for heat map
myPalette <- colorRampPalette(c("darkblue","blue", "white", "red","darkred"))(n = 299) 
#pseudotime<-sort(stromal.cds$Pseudotime)
#plot the heatmap
x<-heatmap.3(
  main = "Stroma genes",
  x=as.matrix(t(cryptolist)),
  Rowv=TRUE,
  #correlation only works 
  distfun=function(x) {as.dist((1-cor(t(x)))/2)} ,
  Colv=TRUE,
  #convert_kmeans_to_dendrogram(Cluster),
  dendrogram = "both",
  trace="none",
  margins =c(9,8),
 # labRow = genes,
#  labCol = samples$rna_match_id,
  col=myPalette,
  scale=c("row"),
  cexRow = 0.8,
 # RowSideColors = (RowSideColors$SideColors),
  RowSideColorsSize = dim(RowSideColors$SideColors)[2]*1.5,
 # ColSideColors = ColSideColors$SideColors,
  ColSideColorsSize = dim(ColSideColors$SideColors)[2],
  lwid = c(1,5),lhei = c(1,5))

legend(xy.coords(x=0,y=.92),
       legend=c("Gene Labels","",RowSideColors$text,
                "Sample Labels","",ColSideColors$text),
       fill=c("white","white",RowSideColors$colors,
              "white","white",ColSideColors$colors),
       border=FALSE, bty="n",
       y.intersp = 0.7, cex=0.6)
```


```{r, fig.width=5, fig.height=3, message=FALSE, warning=FALSE, echo=FALSE}
sorted <- df1[order(df1$percent_change_24h, decreasing=T),]
p <- ggplot(data = sorted, x=symbol,y=percent_change_24h,
            aes(x = symbol,
                y = percent_change_24h) )
p <- p +  geom_point()
p<-p+geom_jitter(alpha=1)
#p <- p +  geom_beeswarm(size=3,alpha = 0.7,cex = 1.2) 
p <- p +  theme(axis.text.x = element_text(angle=30,vjust =.9,hjust = 1))
print(p)
```
